# Generated by Django 5.2.6 on 2025-09-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_animal_pet_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/covers/'),
        ),
    ]
