# Generated by Django 5.2.6 on 2025-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_petallergy_vaccinerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('ADOPTION', 'รอหาบ้าน'), ('LOST', 'กำลังตามหา'), ('OWNED', 'มีเจ้าของแล้ว')], db_index=True, default='OWNED', max_length=10),
        ),
    ]
