# Generated by Django 5.2.6 on 2025-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='เบอร์ติดต่อฉุกเฉิน'),
        ),
        migrations.AddField(
            model_name='pet',
            name='contact_social',
            field=models.TextField(blank=True, verbose_name='ข้อมูลติดต่อ (Facebook, Line, IG)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ลักษณะ/ตำหนิ'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('MALE', 'ตัวผู้'), ('FEMALE', 'ตัวเมีย'), ('UNKNOWN', 'ไม่ระบุเพศ')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='lost_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่หาย'),
        ),
        migrations.AddField(
            model_name='pet',
            name='lost_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='หายจาก (สถานที่)'),
        ),
    ]
