# Generated by Django 5.2.6 on 2025-11-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อมูลนิธิ/องค์กร')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='foundations/logos/', verbose_name='โลโก้')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบายสั้นๆ')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมลติดต่อ')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='เว็บไซต์')),
                ('facebook_url', models.URLField(blank=True, max_length=500, verbose_name='Facebook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงในระบบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foundation / Org',
                'verbose_name_plural': 'Foundations / Orgs',
                'ordering': ['name'],
            },
        ),
    ]
