# Generated by Django 5.2.6 on 2025-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดอายุ'),
        ),
    ]
