# Generated by Django 5.2.6 on 2025-11-19 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอการตอบรับ'), ('APPROVED', 'อนุมัติให้รับเลี้ยง'), ('REJECTED', 'ปฏิเสธ')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='ข้อความ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.adoptionrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
