# Generated by Django 5.2.6 on 2025-11-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_adoptionrequest_status_adoptionrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adopted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ปิดเคส/รับเลี้ยงแล้ว'),
        ),
    ]
