# Generated by Django 5.2.8 on 2025-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_post_adopted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='จังหวัด'),
        ),
    ]
