# Generated by Django 5.2.8 on 2025-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_post_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amphoe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อำเภอ/เขต'),
        ),
        migrations.AddField(
            model_name='post',
            name='tambon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำบล/แขวง'),
        ),
    ]
