# Generated by Django 5.2.8 on 2025-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='org_type',
            field=models.CharField(choices=[('FOUNDATION', 'มูลนิธิ/องค์กรเอกชน'), ('GOVERNMENT', 'หน่วยงานรัฐ (ปศุสัตว์)'), ('HOSPITAL', 'โรงพยาบาลสัตว์')], default='FOUNDATION', max_length=20, verbose_name='ประเภทองค์กร'),
        ),
    ]
