# Generated by Django 5.2.8 on 2026-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_foundation_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
