# Generated by Django 5.2.8 on 2026-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_adoptionrequest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด (ประมาณ)'),
        ),
    ]
